#!/usr/bin/env python3
"""Native checks for predictable actions and the design-psychology improvements."""
from pathlib import Path
exec((Path(__file__).resolve().parent/'e2e-desktop.py').read_text().split('\ntry:\n    new_session()')[0])

def shoot(name):
    subprocess.run(['import','-window','root',str(OUT/f'{name}.png')],check=True)

def park_panel():
    def find_panel():
        candidates=subprocess.check_output(['xdotool','search','--onlyvisible','--class','Daxiong-pet'],text=True).splitlines()
        return next((w for w in candidates if 'WIDTH=360' in subprocess.check_output(['xdotool','getwindowgeometry','--shell',w],text=True)),None)
    wait(lambda:invoke('plugin:window|is_visible',{'label':'playground'}))
    panel_native=wait(find_panel)
    pointer('windowmove',panel_native,870,30)

try:
    new_session();main=command('GET','/window')
    wait(lambda:js("return document.querySelector('.pet-sheet')?.naturalHeight===5616"))
    wait(lambda:invoke('plugin:window|is_visible',{'label':'main'}));time.sleep(.7)
    check('showing intro alone does not mark it learned',js("return !localStorage.getItem('pet-menu-intro-v2')"))
    invoke('set_encounters',{'enabled':False})
    initial=set(command('GET','/window/handles'));invoke('open_playground')
    wait(lambda:len(command('GET','/window/handles'))>len(initial))
    panel=next(iter(set(command('GET','/window/handles'))-initial))
    command('POST','/window',{'handle':panel})
    wait(lambda:js("return !!document.querySelector('[data-testid=play-throw]')"))
    native=pet_native()
    park_panel();pointer('windowmove',native,70,320);time.sleep(.3)
    check('opening panel completes first-use discovery',js("return localStorage.getItem('pet-menu-intro-v2')==='seen'"))
    invoke('plugin:event|listen',{'event':'pet:play','target':{'kind':'Any'},'handler':js('window.__uxPlays=[];return window.__TAURI_INTERNALS__.transformCallback(e=>window.__uxPlays.push(e.payload))')})
    click('飞盘');click('拿出飞盘');wait(lambda:invoke('play_status')['phase']=='ready')
    click('扔飞盘');pointer('mousemove',30,30)
    wait(lambda:invoke('play_status')['phase']=='chasing')
    check('chasing disables restart and removes respawn action',js("return document.querySelector('[data-testid=play-throw]').disabled&&!document.querySelector('[data-testid=play-show]')"))
    check('feeding states interruption and is visually secondary',js("const b=document.querySelector('[data-testid=quick-feed]');return b.textContent==='结束互动，喂块饼干'&&!b.classList.contains('primary')"))
    wait(lambda:invoke('play_status')['phase']=='returned',25)
    command('POST','/window',{'handle':main})
    wait(lambda:js("return document.querySelector('.bubble')?.textContent.includes('飞盘')"),5)
    check('first interaction feedback replaces introductory hint')
    command('POST','/window',{'handle':panel})
    wait(lambda:js("return document.querySelector('[data-testid=play-throw]').textContent==='再扔一次'"))
    check('returned toy exposes clear repeat action',js("return !document.querySelector('[data-testid=play-throw]').disabled"));shoot('returned-controls')
    origin=invoke('play_status')['ball']
    js('window.__uxPlays=[];return true')
    click('扔飞盘');pointer('mousemove',30,30)
    launched=wait(lambda:js("return window.__uxPlays.find(v=>v.phase==='chasing')||null"))
    check('repeat continues from returned location',abs(launched['ball'][0]-origin[0])<=30 and abs(launched['ball'][1]-origin[1])<=30 and launched['catches']==1)
    click('拔河')
    wait(lambda:invoke('play_status')['phase']=='off')
    check('switch provides feedback after cancelling prior game',js("return document.querySelector('.play-panel').textContent.includes('准备拔河')"))
    click('拿出绳子');wait(lambda:invoke('play_status')['phase']=='tug_ready')
    check('active rope no longer offers restarting button',js("return ![...document.querySelectorAll('button')].some(b=>b.textContent==='拿出绳子')"))
    native_click("document.querySelector('[data-testid=quick-feed]')");pointer('mousemove',30,30)
    wait(lambda:invoke('play_status')['phase']=='off')
    check('explicit feed ends interaction and commits once',invoke('companion_status')['treats']==1)
    shoot('feeding-feedback')
    click('怎么玩？');wait(lambda:js("return !!document.querySelector('[data-testid=help-guide]')"))
    check('help can be reopened and explains Mac and close semantics',js("const t=document.querySelector('[data-testid=help-guide]').textContent;return t.includes('双指点按')&&t.includes('会继续当前游戏')"))
    click('知道了');open_more()
    js("const i=document.querySelector('#nickname');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(i,'乔乔');i.dispatchEvent(new Event('input',{bubbles:true}));return true")
    click('记住昵称');wait(lambda:invoke('companion_status')['nickname']=='乔乔')
    check('nickname save gives local success feedback',js("return document.querySelector('[data-testid=memory-success]').textContent.includes('以后叫你乔乔')"))
    shoot('nickname-confirmed')
    check('relationship comes first and numerical records are optional',js("return !!document.querySelector('[data-testid=memory-story]')&&!document.querySelector('.memory-records').open"))
    invoke('set_encounters',{'enabled':True})
    native_click("document.querySelector('[data-testid=quiet-companion]')")
    wait(lambda:invoke('companion_status')['quiet_companion'])
    check('quiet preference preserves the encounter preference',invoke('companion_status')['encounters_enabled'])
    wait(lambda:js("return document.querySelector('[data-testid=encounter-phase]').textContent.includes('暂时暂停')"))
    check('quiet mode visibly explains paused encounters')
    invoke('plugin:event|listen',{'event':'pet:say','target':{'kind':'Any'},'handler':js('window.__quietSays=[];return window.__TAURI_INTERNALS__.transformCallback(e=>window.__quietSays.push(e.payload))')})
    pointer('mousemove',30,30);time.sleep(7)
    check('quiet native runtime has no idle speech or encounters',not any(k in ['idle','wander','water','chime','ball_invite'] for k in js('return window.__quietSays')) and invoke('encounter_status')['kind'] is None)
    before_quiet_play=invoke('play_status')['catches']
    click('飞盘');click('扔飞盘');pointer('mousemove',30,30)
    wait(lambda:invoke('play_status')['phase']=='returned',25)
    check('requested frisbee works while quiet',invoke('play_status')['catches']==before_quiet_play+1)
    command('POST','/window',{'handle':main});wait(lambda:js("return document.querySelector('.bubble')?.textContent.includes('飞盘')"))
    check('quiet mode retains direct interaction feedback')
    command('POST','/window',{'handle':panel});open_more();shoot('quiet-companionship')
    saved_memory=invoke('companion_status')
    exec(ROOT.joinpath('scripts/e2e-memory.py').read_text().split('\nopen_more()\nwait(lambda: js(')[0])
    restart_app();park_panel()
    wait(lambda:js("return document.querySelector('[data-testid=quiet-companion]')?.checked"))
    restored_memory=invoke('companion_status')
    check('real restart retains quiet setting and relationship records',restored_memory['quiet_companion'] and all(restored_memory[k]==saved_memory[k] for k in ['nickname','fetches','affection','treats']))
    native_click("document.querySelector('[data-testid=quiet-companion]')")
    wait(lambda:not invoke('companion_status')['quiet_companion'])
    check('leaving quiet restores original encounter preference',invoke('companion_status')['encounters_enabled'])
    print(json.dumps({'ok':True,'checks':checks},ensure_ascii=False))
    (OUT/'result.json').write_text(json.dumps({'ok':True,'checks':checks},ensure_ascii=False,indent=2))
finally:
    if session:
        command('DELETE','')
