"""Measure generated rope-tip anchors during atlas packing; does not edit pixels."""
import json
from pathlib import Path
import subprocess
import sys

frames, output = map(Path, sys.argv[1:])
anchors = []
for index in range(8):
    rgba = subprocess.check_output(['convert', str(frames / f'frame-{index}.png'), '-depth', '8', 'rgba:-'])
    pixels = [(x, y) for y in range(208) for x in range(192) if rgba[(y * 192 + x) * 4 + 3] >= 128]
    tip_x = (max if index < 4 else min)(x for x, _ in pixels)
    tip_ys = [y for x, y in pixels if x == tip_x]
    anchors.append([tip_x, round((min(tip_ys) + max(tip_ys)) / 2, 1)])
right, left = anchors[:4] * 2, anchors[4:] * 2
output.joinpath('tug-anchors.json').write_text(json.dumps({'right': right, 'left': left}, indent=2) + '\n')
rust = '// Generated by scripts/pack-tug.sh from the visible baked rope tips.\n'
for name, values in [('TUG_RIGHT', right), ('TUG_LEFT', left)]:
    rust += f'const {name}: [(f32,f32);8] = [' + ','.join(f'({x:.1f},{y:.1f})' for x, y in values) + '];\n'
output.joinpath('tug-anchors.rs').write_text(rust)
